// Copies the content schema and its helpers (lib/site) to the Edge Functions (supabase/functions/_shared/site), which
// cannot import from outside their folder once deployed. Run after changing lib/site; `--check` fails if they differ.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const files = ["schema.ts", "collection.ts", "format.ts", "links.ts", "pages.ts", "paths.ts", "labels.ts", "changes.ts", "pricing.ts"];
const target = "supabase/functions/_shared/site";
const header = "// Generated by scripts/sync-shared.mjs from lib/site — edit the original there, not this copy.\n";
const check = process.argv.includes("--check");

mkdirSync(target, { recursive: true });
let stale = [];
for (const file of files) {
  if (!existsSync(`lib/site/${file}`)) continue;
  const content = header + readFileSync(`lib/site/${file}`, "utf8");
  const path = `${target}/${file}`;
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current === content) continue;
  if (check) stale.push(path);
  else writeFileSync(path, content);
}
if (check && stale.length) {
  console.error("Out of date (run node scripts/sync-shared.mjs):", stale.join(", "));
  process.exit(1);
}
console.log(check ? "shared site code is up to date" : "shared site code synced");
